Update qwlroots to fix build with wlroots 17
vioken/waylib pull request #133
Opened 2023-08-24 03:55 UTC by wineee

2023-08-24 05:06 UTC, wineee commented
rbase after https://github.com/vioken/waylib/pull/132

2023-08-28 03:02 UTC, zccrs requested changes

2023-08-28 03:02 UTC, zccrs commented on src/server/qtquick/woutputviewport.cpp
> +    Q_ASSERT_X(texAttr.type == TextureAttrib::INVALID, "QuickOutputCursor::setTexture", "Unknow texture type");
Should is `texAttr.type != TextureAttrib::INVALID` ?

2023-08-28 03:02 UTC, zccrs commented on tests/manual/cursor/main.cpp
> +#include "widget.h"
copyright

2023-08-28 03:02 UTC, zccrs commented on tests/manual/cursor/widget.cpp
> +#include "widget.h"
copyright

2023-08-28 03:02 UTC, zccrs commented on tests/manual/cursor/widget.h
> +#ifndef WIDGET_H
copyright

2023-08-28 05:33 UTC, zccrs approved these changes

2023-08-28 05:47 UTC, merged