Fix wheel event not be send
vioken/waylib pull request #201
Opened 2023-11-03 09:36 UTC by wineee

2023-11-03 09:39 UTC, wineee commented on src/server/kernel/wseat.cpp
> +                        0, //double delta,
We lost this value when wlr_event convert to QEvent

2023-11-07 01:46 UTC, zccrs requested changes

2023-11-07 01:46 UTC, zccrs commented on src/server/kernel/wseat.h
> +class Q_GUI_EXPORT WSeatWheelEvent : public QWheelEvent {
Move to .cpp

2023-11-07 05:09 UTC, zccrs approved these changes

2023-11-07 05:09 UTC, merged