Implement WQuickDecorationMapper
vioken/waylib pull request #214
Opened 2023-11-16 12:05 UTC by justforlxz

2023-11-20 03:52 UTC, zccrs requested changes

2023-11-20 03:52 UTC, zccrs commented on src/server/qtquick/private/wquickdecorationmapper_p.h
> +    static WQuickDecorationMapperAttached *qmlAttachedProperties(QObject *target);
Why add a new class not in WQuickXdgDecorationManager?

2023-11-21 02:15 UTC, zccrs requested changes

2023-11-21 02:15 UTC, zccrs commented on src/server/qtquick/private/wquickxdgdecorationmanager.cpp
> +    Q_EMIT q->surfaceModeChanged(surface, decorations.value(surface, mode));
Why not direct using `mode` value.

2023-11-21 02:15 UTC, zccrs commented on src/server/qtquick/private/wquickxdgdecorationmanager.cpp
> +                d->updateDecorationMode(QWXdgToplevelDecorationV1::from(wlr_decorations));
Why not direct using `decorat`

2023-11-21 02:15 UTC, zccrs commented on src/server/qtquick/private/wquickxdgdecorationmanager.cpp
> +    d->mode = DecidesByClient;
?

2023-11-21 02:15 UTC, zccrs commented on src/server/qtquick/private/wquickxdgdecorationmanager_p.h
> +    Q_PROPERTY(bool enable READ enable NOTIFY enableChanged FINAL)
What is `enable`? `serverDecorationEnabled`?

2023-11-21 02:15 UTC, zccrs commented on src/server/qtquick/private/wquickxdgdecorationmanager_p.h
> +class WAYLIB_SERVER_EXPORT WQuickXdgDecorationMapperAttached : public QObject
`WQuickXdgDecorationManagerAttached`

2023-11-21 02:15 UTC, zccrs commented on src/server/qtquick/private/wquickxdgdecorationmanager.cpp
> +    XDG_DECORATION_MANAGER = this;
````
if (XDG_DECORATION_MANAGER)
    qFatal(...)
````

2023-11-21 06:35 UTC, wineee commented on src/server/qtquick/private/wquickxdgdecorationmanager.cpp
> +#include "qwxdgshell.h"
```suggestion
#include <qwxdgshell.h>
```
and move behind waylib headers

2023-11-21 13:19 UTC, zccrs requested changes

2023-11-21 13:19 UTC, zccrs commented on src/server/qtquick/private/wquickxdgdecorationmanager.cpp
> +}
`Q_EMIT modeChanged(mode);`

2023-11-23 05:18 UTC, zccrs approved these changes

2023-11-23 05:21 UTC, merged