Support wlr output management
vioken/waylib pull request #229
Opened 2023-11-29 07:48 UTC by wineee

2023-12-01 07:27 UTC, zccrs requested changes

2023-12-01 07:27 UTC, zccrs commented on src/server/kernel/woutput.h
> +    Q_PROPERTY(int x READ x WRITE setX NOTIFY xChanged)
Why? The output's position is control in QWOutputLayout, Don't set it in WOutput, you can control position by `OutputItem`.

2023-12-08 01:51 UTC, zccrs requested changes

2023-12-08 01:51 UTC, zccrs commented on src/server/kernel/woutput.h
> +
？

2023-12-08 02:42 UTC, wineee commented on src/server/kernel/woutput.h
> +    void requestTransform(Transform transform);
removed

2023-12-08 02:42 UTC, wineee commented on src/server/qtquick/private/wquickbackend_p.h
> +    Q_INVOKABLE WBackend *wbackend() const;
Yes, don,t need this now

2023-12-08 04:01 UTC, zccrs requested changes

2023-12-08 05:15 UTC, zccrs commented on examples/tinywl/OutputDelegate.qml
> +        waylandOutput.OutputItem.item.x = x;
The root item is `OutputItem`, maybe you can using it.

2023-12-08 06:30 UTC, zccrs approved these changes

2023-12-08 06:30 UTC, merged