Don't change initial position of popup
vioken/waylib pull request #241
Opened 2023-12-19 03:34 UTC by wineee

2023-12-19 08:55 UTC, asterwyx approved these changes
Verified. Works.

2023-12-19 11:45 UTC, zccrs requested changes

2023-12-19 11:45 UTC, zccrs commented on examples/tinywl/StackWorkspace.qml
>                  if (!parentItem)
{}

2023-12-19 11:45 UTC, zccrs commented on examples/tinywl/StackWorkspace.qml
>                  if (!parentItem)
{}

2023-12-20 02:21 UTC, zccrs approved these changes

2023-12-20 02:21 UTC, merged