Fix contentItem size not change after set renderwindow's width/height
vioken/waylib pull request #251
Opened 2024-01-02 05:26 UTC by wineee

This will cause topbar not visable when only one output

2024-01-02 07:01 UTC, zccrs requested changes

2024-01-02 07:01 UTC, zccrs commented on src/server/qtquick/woutputrenderwindow.h
> +    Q_PROPERTY(int width READ width WRITE setWidth NOTIFY widthChanged)
qreal

2024-01-02 07:01 UTC, zccrs commented on src/server/qtquick/woutputrenderwindow.h
> +    void widthChanged(int arg);
Don't add new signal, use QWindow::widthChanged

2024-01-02 07:24 UTC, wineee commented on src/server/qtquick/woutputrenderwindow.h
> +    void widthChanged(int arg);
```
In file included from /home/rewine/dev/waylib/src/server/qtquick/woutputrenderwindow.cpp:1297:
/home/rewine/dev/waylib/build/src/server/waylibserver_autogen/include/moc_woutputrenderwindow.cpp: 在函数‘void checkNotifySignalValidity_CLASSWaylibSCOPEServerSCOPEWOutputRenderWindowENDCLASS(Waylib::Server::WOutputRenderWindow*)’中:
/home/rewine/dev/waylib/build/src/server/waylibserver_autogen/include/moc_woutputrenderwindow.cpp:271:20: 错误：no matching function for call to ‘Waylib::Server::WOutputRenderWindow::widthChanged()’
  271 |     t->widthChanged();
      |     ~~~~~~~~~~~~~~~^~

```

2024-01-02 07:53 UTC, zccrs requested changes

2024-01-02 07:53 UTC, zccrs commented on src/server/qtquick/woutputrenderwindow.cpp
> +    Q_EMIT widthChanged(arg);
Don't emit signal here, connect to contentItem->widthChanged

2024-01-03 08:22 UTC, zccrs approved these changes

2024-01-03 08:22 UTC, merged