fix: build warning
vioken/waylib pull request #280
Opened 2024-03-05 10:30 UTC by Groveer

as title

Log:

2024-03-08 07:54 UTC, BLumia approved these changes

2024-03-11 02:32 UTC, zccrs requested changes

2024-03-11 02:32 UTC, zccrs commented on src/server/kernel/wseat.h
> +    using QObject::eventFilter;
Why?

2024-03-11 02:32 UTC, zccrs commented on src/server/qtquick/private/wquickxdgdecorationmanager.cpp
> -        return decorations.value(surface, WQuickXdgDecorationManager::DecidesByClient);
@wineee

2024-03-11 02:32 UTC, zccrs commented on src/server/qtquick/private/wquickxdgdecorationmanager.cpp
> -    WQuickXdgDecorationManager::DecorationMode mode = WQuickXdgDecorationManager::DecidesByClient;
@wineee

2024-03-11 02:32 UTC, zccrs commented on src/server/qtquick/private/wquickxdgdecorationmanager.cpp
> +            mode = WQuickXdgDecorationManager::Server;
break;

2024-03-11 02:32 UTC, zccrs commented on src/server/qtquick/private/wquickxdgdecorationmanager_p.h
>      enum DecorationMode {
@wineee

2024-03-11 05:05 UTC, zccrs approved these changes

2024-03-11 05:06 UTC, merged