Feat: expose output specified on creation to qml
vioken/waylib pull request #296
Opened 2024-03-25 09:45 UTC by ZhongYic00

Only configured on creation, so use CONSTANT qproperty
see https://wayland.app/protocols/wlr-layer-shell-unstable-v1#zwlr_layer_shell_v1:request:get_layer_surface

2024-03-25 10:21 UTC, wineee approved these changes

2024-03-25 10:23 UTC, wineee requested changes

2024-03-25 10:23 UTC, wineee commented on src/server/kernel/wlayersurface.cpp
> +    output = WOutput::fromHandle(QWOutput::from(nativeHandle()->output));
check `nativeHandle()->output` is NULL

2024-03-26 02:29 UTC, zccrs approved these changes

2024-03-26 02:29 UTC, merged