fix: warning [-Wformat-extra-args]
vioken/waylib pull request #304
Opened 2024-04-16 08:11 UTC by Groveer

it cannot compile with clang++

Log:

2024-04-16 08:11 UTC, wineee approved these changes

2024-04-18 02:40 UTC, zccrs requested changes

2024-04-18 02:40 UTC, zccrs commented on src/server/qtquick/wsurfaceitem.cpp
> +            qFatal() <<"SurfaceItem's delegate must is Item";
Missing space at `<<` after.

2024-04-18 02:52 UTC, zccrs approved these changes

2024-04-18 02:52 UTC, merged