Fix LayerShell crash in Qt6.7
vioken/waylib pull request #319
Opened 2024-05-15 10:00 UTC by justforlxz

Qt 6.7 will perform some actions in the constructor of QQuickItem. Since we provide our own private object, this will cause the target we want to manage not to be initialized in the public object, so the target is moved to the private object for management.

2024-05-15 10:19 UTC, wineee approved these changes

2024-05-15 10:25 UTC, zccrs requested changes

2024-05-15 10:25 UTC, zccrs commented on src/server/qtquick/private/wquickcoordmapper.cpp
> +    WQuickObserver *m_target;
Remove `m_`

2024-05-15 10:25 UTC, zccrs commented on src/server/qtquick/private/wquickcoordmapper_p.h
> +    WQuickObserver *target() const;
Don't add a new function in header file.

2024-05-15 10:25 UTC, zccrs commented on src/server/qtquick/private/wquickcoordmapper_p.h
> +    WQuickObserver *target() const;
Use `WQuickObserverPrivate::get(...)->target` replace, like as QQuickItemPrivate::get function.

2024-05-16 03:33 UTC, zccrs requested changes

2024-05-16 03:33 UTC, zccrs commented on src/server/qtquick/private/wquickcoordmapper.cpp
> +    static const WQuickCoordMapperPrivate* get(const WQuickCoordMapper *item) { return item->d_func(); }
missing `const`

2024-05-16 03:33 UTC, zccrs commented on src/server/qtquick/private/wquickcoordmapper.cpp
> +    static WQuickCoordMapperPrivate* get(WQuickCoordMapper *item) { return item->d_func(); }
`WQuickCoordMapperPrivate *get`

2024-05-16 03:43 UTC, zccrs approved these changes

2024-05-16 05:07 UTC, justforlxz commented
/check obs

2024-05-16 05:17 UTC, merged