Add support for xdg-output-v1
vioken/waylib pull request #325
Opened 2024-05-17 10:15 UTC by Dami-star

2024-05-20 02:01 UTC, wineee requested changes

2024-05-20 13:10 UTC, Dami-star commented on src/server/qtquick/private/wquickxdgoutput.cpp
> +    wlr_xdg_output_manager_v1_create(server()->handle()->handle(), layout->handle());
done

2024-05-20 13:10 UTC, Dami-star commented on src/server/qtquick/private/wquickxdgoutput_p.h
> +    void create(WOutputLayout *layout);
done

2024-05-21 02:25 UTC, wineee requested changes

2024-05-21 02:25 UTC, wineee commented on src/server/qtquick/private/wquickxdgoutput.cpp
> +        QWXdgOutputManagerV1::create(server()->handle(), d->layout);
else qWarning

2024-05-21 02:25 UTC, wineee commented on src/server/qtquick/private/wquickxdgoutput.cpp
> +    if (d->layout == layout)
```
if (d->layout) {
  qmlWarning(this) << "Trying to set output layout for xdg output manager twice. Ignore this request";
  return;
}
```

2024-05-21 02:53 UTC, wineee requested changes

2024-05-21 02:53 UTC, wineee commented on examples/tinywl/Main.qml
> +                console.info("XdgOutputManager")
remove

2024-05-21 02:55 UTC, wineee requested changes

2024-05-21 02:55 UTC, wineee commented on src/server/qtquick/private/wquickxdgoutput_p.h
> +
```suggestion
```

2024-05-21 02:55 UTC, wineee commented on src/server/qtquick/private/wquickxdgoutput_p.h
> +
```suggestion
```

2024-05-21 03:17 UTC, Dami-star commented on src/server/qtquick/private/wquickxdgoutput.cpp
> +        QWXdgOutputManagerV1::create(server()->handle(), d->layout);
done

2024-05-21 03:17 UTC, Dami-star commented on src/server/qtquick/private/wquickxdgoutput.cpp
> +    if (d->layout == layout)
done

2024-05-21 03:18 UTC, Dami-star commented on examples/tinywl/Main.qml
> +                console.info("XdgOutputManager")
done

2024-05-21 03:18 UTC, Dami-star commented on src/server/qtquick/private/wquickxdgoutput_p.h
> +
done

2024-05-21 03:18 UTC, Dami-star commented on src/server/qtquick/private/wquickxdgoutput_p.h
> +
done

2024-05-21 03:32 UTC, wineee requested changes

2024-05-21 03:32 UTC, wineee commented on examples/tinywl/Main.qml
> +            id: xdgoutputmanager
```suggestion
            id: xdgOutputManager
```

2024-05-21 03:32 UTC, wineee commented on src/server/qtquick/private/wquickxdgoutput.cpp
> +#include "wxdgsurface.h"
wsurface and wxdgsurface should unused?

2024-05-21 03:42 UTC, Dami-star commented on examples/tinywl/Main.qml
> +            id: xdgoutputmanager
done

2024-05-21 03:42 UTC, Dami-star commented on src/server/qtquick/private/wquickxdgoutput.cpp
> +#include "wxdgsurface.h"
done

2024-05-21 05:10 UTC, wineee requested changes

2024-05-21 05:10 UTC, wineee commented on src/server/qtquick/private/wquickxdgoutput.cpp
> +        qWarning() << "Need to set output layout !";
```suggestion
        qWarning() << "Output layout not set, xdg output manager will never be created!";
```

2024-05-21 05:12 UTC, wineee commented
also need rebase to have https://github.com/vioken/waylib/pull/330

2024-05-21 05:24 UTC, Dami-star commented on src/server/qtquick/private/wquickxdgoutput.cpp
> +        qWarning() << "Need to set output layout !";
done

2024-05-21 05:27 UTC, wineee approved these changes
LGTM, @zccrs

2024-05-21 06:08 UTC, Dami-star commented on src/server/qtquick/private/wquickxdgoutput.cpp
> +    WQuickWaylandServerInterface(parent)
done

2024-05-21 06:08 UTC, Dami-star commented on src/server/qtquick/private/wquickxdgoutput.cpp
> +    if(d->layout)
done

2024-05-21 09:38 UTC, zccrs approved these changes

2024-05-21 10:08 UTC, wineee commented
?? @Dami-star  https://github.com/vioken/waylib/compare/4c010bec24731af50a7d175bdb11c61fa0696874..ee0fc5df75c108e9e04e706a493efedf11631c2d

2024-05-21 10:22 UTC, zccrs approved these changes

2024-05-22 01:25 UTC, merged