feat: notify surface fractional scale
vioken/waylib pull request #328
Opened 2024-05-20 08:06 UTC by lychee-yycy

2024-05-20 08:11 UTC, wineee requested changes

2024-05-20 08:11 UTC, wineee commented on src/server/qtquick/private/wquickfractionalscalemanagerv1.cpp
> +#include "wglobal.h"
Copyright

2024-05-20 08:11 UTC, wineee commented on src/server/qtquick/private/wquickfractionalscalemanagerv1_p.h
> +// Copyright (C) 2023 YaoBing Xiao <zhangdingyuan@uniontech.com>.
2024

2024-05-20 10:01 UTC, zccrs requested changes
Update qwlroots for submodule

2024-05-22 05:22 UTC, zccrs approved these changes

2024-05-22 09:30 UTC, zccrs approved these changes

2024-05-22 09:30 UTC, merged