feat: supprort for session lock manager protocol
vioken/waylib pull request #347
Opened 2024-05-27 10:03 UTC by ssk-wh

2024-05-28 01:42 UTC, zccrs requested changes

2024-05-28 01:42 UTC, zccrs commented on src/server/qtquick/private/wquicksessionlockmanager.cpp
> +    : Waylib::Server::WQuickWaylandServerInterface(parent)
Remove namespace

2024-05-28 01:42 UTC, zccrs commented on src/server/qtquick/private/wquicksessionlockmanager_p.h
> +// Copyright (C) 2024 Lu YaNing <luyaning@uniontech.org>.
Why is not `ssk-wh`?

2024-05-28 02:01 UTC, zccrs requested changes
Where call `sendLocked`?

2024-05-28 02:51 UTC, ssk-wh commented
> Where call `sendLocked`?

It has been added, called after a locksurface request

2025-09-18 12:29 UTC, zccrs commented
这个提交应该不需要了，我先关闭了，如果有必要可以请求reopen

2025-09-18 12:29 UTC, closed without merging