feat: Implement WQuickSecurityContextManagerV1
vioken/waylib pull request #352
Opened 2024-05-28 02:56 UTC by lychee-yycy

2024-05-28 03:11 UTC, zorowk commented on src/server/qtquick/private/wquicksecuritycontextmanagerv1_p.h
> +    class WQuickSecurityContextManagerV1Private;
indent is not aligned

2024-05-28 03:25 UTC, lychee-yycy commented on src/server/qtquick/private/wquicksecuritycontextmanagerv1_p.h
> +    class WQuickSecurityContextManagerV1Private;
done

2024-05-28 07:20 UTC, zccrs requested changes

2024-05-28 07:20 UTC, zccrs commented on src/server/qtquick/private/wquickfractionalscalemanagerv1.cpp
> +        qFatal("There are multiple instances of WQuickFractionalScaleManagerV1");
Fix in a new commit.

2024-07-03 05:17 UTC, lychee-yycy commented
qwlroots refactored, abandoned

2024-07-03 05:17 UTC, closed without merging