fix: debian package missing dependencies
vioken/waylib pull request #378
Opened 2024-06-14 09:20 UTC by lbwtw

add qml6-module-qtquick-effects build-depends.

2024-06-17 01:34 UTC, zccrs approved these changes

2024-06-17 01:35 UTC, zccrs requested changes

2024-06-17 01:35 UTC, zccrs commented on debian/control
> + qml6-module-qtquick-effects
Should is `Depends`, is not `Build-Depends`?

2024-06-24 07:27 UTC, wineee commented
Error rebase?

2024-06-24 08:39 UTC, closed without merging