feat: add utility function in render window
vioken/waylib pull request #406
Opened 2024-07-11 02:52 UTC by asterwyx

Get paint order items from a root.

2024-07-11 08:41 UTC, zccrs requested changes

2024-07-11 08:41 UTC, zccrs commented on src/server/qtquick/woutputrenderwindow.cpp
> +template<typename UnaryFunc>
Can't use template in cpp.
You can use std::function to replace.

2024-07-11 08:45 UTC, zccrs requested changes

2024-07-11 08:45 UTC, zccrs commented on src/server/qtquick/woutputrenderwindow.cpp
> +    QStack<QQuickItem *> nodes;
Should use QQueue?

2024-07-11 10:10 UTC, asterwyx commented on src/server/qtquick/woutputrenderwindow.cpp
> +    QStack<QQuickItem *> nodes;
Preorder traversal use a stack.

2024-07-12 02:15 UTC, zccrs approved these changes

2024-07-12 02:15 UTC, merged