Clear up foreigntoplevelv1 and support xwayland
vioken/waylib pull request #472
Opened 2024-08-23 09:36 UTC by wineee

2024-08-23 10:00 UTC, wineee commented
tested by lswt

2024-08-26 02:24 UTC, zccrs requested changes

2024-08-26 02:24 UTC, zccrs commented on examples/tinywl/main.cpp
> +        if (!s->isPopup()) {
How to close popup surface?

2024-08-26 03:53 UTC, zccrs requested changes

2024-08-26 03:53 UTC, zccrs commented on src/server/protocols/wxdgsurface.cpp
> +        popup->deleteLater();
Does the wlr_xdg_popup will following destroy?

2024-08-26 03:53 UTC, zccrs commented on examples/tinywl/main.cpp
> +void Helper::closeSurface(WSurface *surface)
remove?

2024-08-26 08:26 UTC, zccrs approved these changes

2024-08-26 08:26 UTC, merged