Fix missing HoverEnter event to next Object after pointerFocusEventOb…
vioken/waylib pull request #529
Opened 2024-10-30 05:33 UTC by wineee

…ject destroyed

2024-10-30 09:43 UTC, zccrs requested changes

2024-10-30 09:43 UTC, zccrs commented on src/server/kernel/wseat.cpp
> +                // Qt missing HoverEnter event to next Object after pointerFocusEventObject destroyed
See frameSynchronousHoverEnabled

2024-10-30 09:47 UTC, zccrs requested changes

2024-10-30 09:47 UTC, zccrs commented on src/server/kernel/wseat.cpp
> +                               Qt::NoModifier);
Why is Qt::NoModifier

2024-10-30 09:47 UTC, zccrs commented on src/server/kernel/wseat.cpp
> +                QHoverEvent hoverEvent(QEvent::HoverEnter, QPointF(0,0), cursor->position(), cursor->position(),
Why scene position is 0,0

2024-11-08 08:45 UTC, wineee commented
Seems https://github.com/vioken/waylib/pull/523 fixed it

2024-11-08 08:45 UTC, closed without merging