fix: texture invalid in non-live state
vioken/waylib pull request #560
Opened 2024-11-28 09:55 UTC by asterwyx

Buffer update is not controlled by live property. Previous buffer is not refered, thus might be destroyed. Pends new buffer in non-live state.

2024-11-28 10:11 UTC, zccrs requested changes

2024-11-28 10:11 UTC, zccrs commented on src/server/qtquick/wsurfaceitem.cpp
> +            buffer->lock();
the lock must before release to ensure the buffer is valid

2024-11-28 10:11 UTC, zccrs commented on src/server/qtquick/wsurfaceitem.cpp
> +            buffer.reset(pendingBuffer.release());
the buffer maybe drop on release

2024-11-29 01:44 UTC, zccrs requested changes

2024-11-29 01:44 UTC, zccrs commented on src/server/qtquick/wsurfaceitem.cpp
> +            pendingBuffer->lock();
````
buffer->reset(pendingBuffer.get());
buffer->lock();
pendingBuffer.reset();
````

2024-11-29 01:51 UTC, zccrs commented on src/server/qtquick/wsurfaceitem.cpp
> +            pendingBuffer->lock();
Maybe only need `buffer.reset(pendingbuffer.release())`

2024-11-29 02:07 UTC, asterwyx commented on src/server/qtquick/wsurfaceitem.cpp
> +            pendingBuffer->lock();
Done.

2024-11-29 02:10 UTC, zccrs approved these changes

2024-11-29 02:10 UTC, merged