feat: add wrappointer
vioken/waylib pull request #591
Opened 2024-12-12 03:52 UTC by asterwyx

Add WrapPointer used for WrapObject.

2024-12-12 05:48 UTC, wineee approved these changes

2024-12-16 05:22 UTC, zccrs requested changes

2024-12-16 05:22 UTC, zccrs commented on src/server/utils/WrapPointer
WWrapPointer

2024-12-16 05:22 UTC, zccrs commented on src/server/utils/wrappointer.h
rename to `wwrappointer.h`, or define it in `wglobal.h` is not in a new file.

2024-12-18 09:34 UTC, zccrs approved these changes

2024-12-18 09:34 UTC, merged